name: teste

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar o código
        uses: actions/checkout@v2

      - name: Executar comandos
        run: |
          echo "Hello, world!"
